### ISSUE TITLE
"Unhandled event loop exception" in file context menu

### ISSUE THREAD

**Issue by Archangel1C** [RolandoMagico/ContextQuickie2#1] opened 2021-01-11 10:54 UTC
When right-clicking on a file (tried .sql and .java) multiple (18) "Unhandled event loop exception" are logged. Also the "Compare with" menu (maybe more) is gone, maybe just because the menu creation process is disrupted. After uninstall the menu reappears.

**Eclipse version**
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

**Used ContextQuickie features**
?

**Session data for stacktrace**
eclipse.buildId=4.11.0.I20190307-0500
java.version=12-BellSoft
java.vendor=BellSoft
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE

**Stack trace**
java.lang.NoClassDefFoundError: Could not initialize class explorercontextmenu.menu.ExplorerContextMenu
	at contextquickie2.plugin.MenuBuilder.getContributionItems(MenuBuilder.java:123)
	at org.eclipse.ui.actions.CompoundContributionItem.getContributionItemsToFill(CompoundContributionItem.java:83)
	at org.eclipse.ui.actions.CompoundContributionItem.fill(CompoundContributionItem.java:57)
	at org.eclipse.ui.internal.menus.DynamicMenuContributionItem.fill(DynamicMenuContributionItem.java:150)
	at org.eclipse.jface.action.MenuManager.doItemFill(MenuManager.java:731)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:813)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:672)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.scheduleManagerUpdate(MenuManagerRenderer.java:1222)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.processContents(MenuManagerRenderer.java:652)
	at org.eclipse.ui.internal.PopupMenuExtender.addMenuContributions(PopupMenuExtender.java:415)
	at org.eclipse.ui.internal.PopupMenuExtender.menuAboutToShow(PopupMenuExtender.java:385)
	at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:342)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:473)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:468)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:500)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:5148)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4797)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1502)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2152)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.TrackPopupMenu(Native Method)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:253)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:3985)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3541)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.views.log.EventDetailsDialog.open(EventDetailsDialog.java:191)
	at org.eclipse.ui.internal.views.log.EventDetailsDialogAction.run(EventDetailsDialogAction.java:102)
	at org.eclipse.ui.internal.views.log.LogView.lambda$2(LogView.java:565)
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:830)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1518)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1260)
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:253)
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:251)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:310)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)

**Comment by RolandoMagico** [comment] 2021-01-11 11:26
Hello @Archangel1C ,
I did a short test with the eclipse and JRE version you mentioned but don't get that error. Which version of ContextQuickie2 do you use? I tried   ContextQuickie2	0.6.1.202012240817.
Best Regards
Roland

**Comment by Archangel1C** [comment] 2021-01-11 13:02
Oh, dammit. I included the version in the bug report, but somehow it got lost...
I think it was the same version as yours - installed it via eclipse marketplace.

Maybe it conflicts with some other plugin I use...

**Comment by RolandoMagico** [comment] 2021-01-11 13:45
Hello @Archangel1C ,
according to the call stack it looks like the exception is caused by my plugin. If you installed from the marketplace in the last days, you should have the latest version.
Is there any way to reproduce the problem? Can you tell me which further plugins you installed, which proect type you're using and in which view (Project Explorer, ...) the exception is raised?
Additional questions: 
- Do you have any special explorer context menu extension? Can you provide a screenshot of the context menu in the explorer for the same files you selected in eclipse?
- Is it the same behaviour if you change the ContextQuickie2 Settings as shown in the screenshot:
![image](https://user-images.githubusercontent.com/75312877/104226003-6e027c80-5447-11eb-951a-b6801c432da9.png)

BR
Roland

**Comment by Archangel1C** [comment] 2021-01-11 22:24
Hey,
I just reinstalled it and can confirm, the version is 0.6.1.202012240817 .

I use the Package Explorer view, but it also happens in Project Explorer.

Same behaviour with all Context Quickie2 settings unchecked.

All my plugins from the Eclipse Installation Details page:
[plugins.log](https://github.com/RolandoMagico/ContextQuickie2/files/5798484/plugins.log)

Screenshot context menu:
![image](https://user-images.githubusercontent.com/12956838/104245184-1a525c00-5464-11eb-8480-91ed2b3c93ee.png)

**Comment by RolandoMagico** [comment] 2021-01-12 06:20
Hi @Archangel1C,
Installed your plugins but still cannot reproduce it. Do you have limited access to the registry?
is it possible to provide the eclipse installation (without the workspace) so I can attach it to the debugger?
Otherwise, I'll try to provide a debug version with more output.

BR
Roland

**Comment by Archangel1C** [comment] 2021-01-13 00:26
I just started Eclipse as administrator, still the error persists, so I don't think registry access is a problem.

I uploaded my eclipse installation here (expires in 7 days): https://we.tl/t-7vUvPEHsN7

**Comment by RolandoMagico** [comment] 2021-01-13 06:39
Hello @Archangel1C ,
does this installation require any special environment?
When I just run it as provided nothing is happening. I tried to replace eclipse.ini with the default one but then Eclipse stops responding on the splash screen during startup.
BR
Roland

**Comment by Archangel1C** [comment] 2021-01-13 08:08
Not that I know of, but I remember (and just tried), that for some reason the **startup process really takes a while** (few minutes). At the time it seemed to me, that this is dependent on the JRE used, but I'm not sure.

I made a change to the installation by adding the `mods` directory (glassfish jaxb-runtime-2.3.2 + dependencies), which is referenced in the `eclipse.ini`; I think it was because of some plugin, which was written against Java 1.8, I guess, which had JAXB on the classpath.

**Comment by RolandoMagico** [comment] 2021-01-13 11:45
Hi @Archangel1C ,
got it, just waiting makes the difference. I can start your eclipse installation now and I also can open the context menu without error message:
![image](https://user-images.githubusercontent.com/75312877/104447921-c4350400-559c-11eb-9fda-b859da0f4c2b.png)


Does the problem also occur with a simple project (something like you can see in the screenshot)?

If yes, can you clone/download https://github.com/RolandoMagico/ExplorerContextMenu and execute ExplorerContextMenu\Source\ExplorerContextMenu.Console\bin\Release\x64\ExplorerContextMenu.Console.exe and pass the path to the file/folder you selected in Eclipse to the application:
![image](https://user-images.githubusercontent.com/75312877/104448282-3dccf200-559d-11eb-8e39-71846b6a9850.png)

**Comment by Archangel1C** [comment] 2021-01-18 12:45
With the ExplorerContextMenu project I was able to find the problem: my system was missing the file `VCRUNTIME140_1.dll` from the Visual C++ redistributable. After installing it from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) (specifically in my case [vs16](https://aka.ms/vs/16/release/vc_redist.x64.exe)) all worked fine.

Would be good, if the error message (see screenshot) would be logged in Eclipse Error Log view, maybe also shown in UI.

![error-VCRUNTIME140_1 dll](https://user-images.githubusercontent.com/12956838/104917189-5e2cf000-5993-11eb-9c8e-a2f8c28ac203.jpg)

**Comment by RolandoMagico** [comment] 2021-01-27 18:51
Fixed in version 0.6.2

**Closed as completed by RolandoMagico** 2021-01-27 18:51 UTC
